### ISSUE TITLE
Ошибка импорта

### ISSUE THREAD

**Issue by KVDcorp** [ButCheR-PRO/HamsterKombatBot#2]
Все работало до того момента, когда я скопировал твои файлы в оригинальную папку
Activating virtual environment...
Starting the bot...
Traceback (most recent call last):
  File "C:\Users\user\Desktop\HamsterKombatBot-main\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "C:\Users\user\Desktop\HamsterKombatBot-main\bot\utils\__init__.py", line 4, in <module>
    from . import launcher
  File "C:\Users\user\Desktop\HamsterKombatBot-main\bot\utils\launcher.py", line 7, in <module>
    from bot.config import settings
  File "C:\Users\user\Desktop\HamsterKombatBot-main\bot\config\__init__.py", line 1, in <module>
    from .config import settings
ModuleNotFoundError: No module named 'bot.config.config'
Для продолжения нажмите любую клавишу . . .

**Comment by KVDcorp** [comment]
Просто исчез конфиг куда-то, но я его вернул и теперь он хочет увидеть файл с  апи телеграма. id,hash лежат где надо, зачем он обращается?..

Traceback (most recent call last):
  File "C:\Users\user\Desktop\HamsterKombatBot-main\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "C:\Users\user\Desktop\HamsterKombatBot-main\bot\utils\__init__.py", line 4, in <module>
    from . import launcher
  File "C:\Users\user\Desktop\HamsterKombatBot-main\bot\utils\launcher.py", line 11, in <module>
    from bot.core.tapper import run_tapper
  File "C:\Users\user\Desktop\HamsterKombatBot-main\bot\core\tapper.py", line 12, in <module>
    from bot.api.telegram import get_me_telegram
ModuleNotFoundError: No module named 'bot.api.telegram'
